// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Giraffe.SerilogExtensions")>]
[<assembly: AssemblyProductAttribute("Giraffe.SerilogExtensions")>]
[<assembly: AssemblyVersionAttribute("1.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2018-12-23T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("1.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","27627af278675c1bb4b8773152ea944d89fc99cf")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Giraffe.SerilogExtensions"
    let [<Literal>] AssemblyProduct = "Giraffe.SerilogExtensions"
    let [<Literal>] AssemblyVersion = "1.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2018-12-23T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "1.1.0"
    let [<Literal>] AssemblyInformationalVersion = "1.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "27627af278675c1bb4b8773152ea944d89fc99cf"
